# Generated by Django 3.1.7 on 2021-04-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210418_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
